workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @react-native/metro-config metro-react-native-babel-preset --save-dev
      - name: Setup Android Structure
        script: |
          echo '{"name": "SuppliesTracker","displayName": "Supplies Tracker"}' > app.json
          cd android
          mkdir -p app/src/main/java/com/suppliestracker app/src/main/res/values app/src/main/assets gradle/wrapper

          # Setup Gradle Wrapper complet
          curl -L https://raw.githubusercontent.com/gradle/gradle/v8.0.2/gradlew -o gradlew
          curl -L https://raw.githubusercontent.com/gradle/gradle/v8.0.2/gradle/wrapper/gradle-wrapper.jar -o gradle/wrapper/gradle-wrapper.jar
          printf "distributionBase=GRADLE_USER_HOME\ndistributionPath=wrapper/dists\nzipStoreBase=GRADLE_USER_HOME\nzipStorePath=wrapper/dists\ndistributionUrl=https\://services.gradle.org/distributions/gradle-8.0.2-all.zip" > gradle/wrapper/gradle-wrapper.properties
          chmod +x gradlew

          # MainActivity Java
          cat <<EOF > app/src/main/java/com/suppliestracker/MainActivity.java
          package com.suppliestracker;
          import com.facebook.react.ReactActivity;
          public class MainActivity extends ReactActivity {
            @Override
            protected String getMainComponentName() { return "SuppliesTracker"; }
          }
          EOF
          
          # Thème & Manifest
          echo '<resources><style name="AppTheme" parent="android:Theme.Material.Light.NoActionBar"></style></resources>' > app/src/main/res/values/styles.xml
          cat <<EOF > app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.suppliestracker">
              <application android:label="Supplies Tracker" android:theme="@style/AppTheme">
                  <activity android:name=".MainActivity" android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" /><category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF
      - name: Bundle JavaScript (The Offline Core)
        script: |
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - ton-email@ici.com
