workflows:
  android-apk:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20.x  # Passage à une version plus stable sur Codemagic
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android APK
        script: |
          # Accède au dossier android et compile l'APK
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - votre-email@domaine.com
