workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup Project Structure
        script: |
          # 1. On se déplace dans le dossier parent pour créer un projet propre
          cd ..
          rm -rf clean_project
          
          # 2. Création du projet dans un dossier isolé (pour éviter les conflits)
          npx react-native@0.72.6 init SuppliesTracker --version 0.72.6 --skip-install --npm --non-interactive
          
          # 3. On rapatrie TOUS les fichiers générés dans le dossier de build de Codemagic
          cp -R SuppliesTracker/* $CM_BUILD_DIR/
          
          # 4. On revient dans le dossier de build
          cd $CM_BUILD_DIR
          
          # 5. On remplace le App.js par votre code (App (1).js)
          cp "App (1).js" App.js || true
          
          # 6. Installation des dépendances
          npm install
          npm install react-native-sqlite-storage lucide-react-native react-native-svg react-native-linear-gradient react-native-image-picker react-native-signature-canvas react-native-webview

      - name: Bundle JavaScript
        script: |
          # On s'assure que le dossier de destination existe
          mkdir -p android/app/src/main/assets
          
          # On génère le bundle JS
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build APK
        script: |
          cd android
          # Création du wrapper Gradle s'il a été oublié
          gradle wrapper --gradle-version 8.0.2
          chmod +x gradlew
          
          # Augmentation de la mémoire
          export GRADLE_OPTS="-Xmx2048m -Xss4m"
          ./gradlew assembleDebug --no-daemon
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - votre-email@exemple.com
