workflows:
  android-apk:
    name: Build SuppliesTracker APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup and Install
        script: |
          sdk use java 17.0.7-sem || true
          cp "App (1).js" App.js || true
          npm install --quiet
          
          rm -rf android
          mkdir -p android/app/src/main/java/com/suppliestracker
          mkdir -p android/app/src/main/res/values
          mkdir -p android/app/src/main/assets

          echo "rootProject.name = 'SuppliesTracker'" > android/settings.gradle
          echo "include ':app'" >> android/settings.gradle

          cat <<EOF > android/build.gradle
          buildscript {
              repositories { google(); mavenCentral() }
              dependencies { classpath("com.android.tools.build:gradle:7.4.2") }
          }
          allprojects {
              repositories { 
                  google()
                  mavenCentral()
                  maven { url "$CM_BUILD_DIR/node_modules/react-native/android" } 
              }
          }
          EOF

          cat <<EOF > android/app/build.gradle
          apply plugin: "com.android.application"
          android {
              namespace "com.suppliestracker"
              compileSdkVersion 33
              defaultConfig {
                  applicationId "com.suppliestracker"
                  minSdkVersion 21
                  targetSdkVersion 33
                  versionCode 1
                  versionName "1.0"
              }
              // Force le nom de l'APK pour le retrouver facilement
              project.archivesBaseName = "SuppliesTracker"
          }
          dependencies {
              implementation "com.facebook.react:react-android:0.72.6"
              implementation "com.facebook.react:hermes-android:0.72.6"
              implementation "androidx.appcompat:appcompat:1.4.1"
          }
          EOF

          cat <<EOF > android/app/src/main/java/com/suppliestracker/MainActivity.java
          package com.suppliestracker;
          import com.facebook.react.ReactActivity;
          public class MainActivity extends ReactActivity {
            @Override protected String getMainComponentName() { return "SuppliesTracker"; }
          }
          EOF

          cat <<EOF > android/app/src/main/java/com/suppliestracker/MainApplication.java
          package com.suppliestracker;
          import android.app.Application;
          import com.facebook.react.ReactApplication;
          import com.facebook.react.ReactNativeHost;
          import com.facebook.react.ReactPackage;
          import com.facebook.react.shell.MainReactPackage;
          import com.facebook.soloader.SoLoader;
          import java.util.Arrays;
          import java.util.List;
          public class MainApplication extends Application implements ReactApplication {
            private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
              @Override public boolean getUseDeveloperSupport() { return false; }
              @Override protected List<ReactPackage> getPackages() { return Arrays.<ReactPackage>asList(new MainReactPackage()); }
              @Override protected String getJSMainModuleName() { return "index"; }
            };
            @Override public ReactNativeHost getReactNativeHost() { return mReactNativeHost; }
            @Override public void onCreate() { super.onCreate(); SoLoader.init(this, false); }
          }
          EOF

          cat <<EOF > android/app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.suppliestracker">
              <application android:name=".MainApplication" android:label="SuppliesTracker" android:theme="@style/Theme.AppCompat.Light.NoActionBar">
                  <activity android:name=".MainActivity" android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF

      - name: Build APK
        script: |
          npx react-native bundle --platform android --dev false --entry-file App.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

          cd android
          gradle wrapper --gradle-version 7.5
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon

          # On liste tous les fichiers .apk créés pour le debug dans les logs
          echo "Recherche des APKs générés :"
          find . -name "*.apk"

    artifacts:
      # Recherche récursive de TOUS les APKs dans n'importe quel dossier
      - "**/build/outputs/apk/**/*.apk"
