workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup Project Structure
        script: |
          # 1. Sauvegarde de votre code précieux
          cp "App (1).js" ../App.backup.js || true
          cp index.js ../index.backup.js || true
          
          # 2. Nettoyage total du répertoire de travail
          rm -rf *
          
          # 3. Création du projet dans le dossier courant (vide maintenant)
          # On ne met pas de nom de projet pour forcer l'init ici
          npx react-native@0.72.6 init SuppliesTracker --version 0.72.6 --skip-install --npm --directory .
          
          # 4. Restauration de votre code par-dessus le template
          mv ../App.backup.js App.js
          mv ../index.backup.js index.js
          
          # 5. Installation des dépendances spécifiques
          npm install
          npm install react-native-sqlite-storage lucide-react-native react-native-svg react-native-linear-gradient react-native-image-picker react-native-signature-canvas react-native-webview
          
          # 6. Génération du moteur Gradle
          cd android && gradle wrapper --gradle-version 8.0.2 && cd ..

      - name: Bundle JavaScript
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          export GRADLE_OPTS="-Xmx2048m -Xss4m"
          ./gradlew assembleDebug --no-daemon
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - votre-email@exemple.com
