workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup Environment
        script: |
          # 1. Sauvegarde de ton code App.js
          cp App.js ../App.js.backup
          
          # 2. Suppression des restes qui font échouer le build
          rm -rf android
          
          # 3. Création du châssis mobile officiel (version stable 0.72.6)
          npx react-native init SuppliesApp --version 0.72.6 --skip-install --npm
          
          # 4. On déplace les fichiers du projet neuf à la racine
          cp -r SuppliesApp/* .
          
          # 5. On réinjecte ton code métier (Offline)
          mv ../App.js.backup App.js
          
          # 6. Installation des drivers SQLite
          npm install
      - name: Build APK
        script: |
          chmod +x android/gradlew
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - ton-email@ici.com
