workflows:
  android-apk:
    name: Build Android APK
    instance_type: mac_mini_m1
    scripts:
      - name: Set up Node.js
        script: | 
          brew install node@20
          brew link --overwrite node@20
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - votre-email@exemple.com
