workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install react-native-sqlite-storage lucide-react-native react-native-svg react-native-linear-gradient react-native-image-picker react-native-signature-canvas react-native-webview
      - name: Setup Android Structure & Java
        script: |
          cd android
          # 1. Création des dossiers Java (indispensable)
          mkdir -p app/src/main/java/com/suppliestracker
          mkdir -p app/src/main/res/values
          mkdir -p app/src/main/assets
          
          # 2. Création de la MainActivity (Le pont vers ton JS)
          cat <<EOF > app/src/main/java/com/suppliestracker/MainActivity.java
          package com.suppliestracker;
          import com.facebook.react.ReactActivity;
          public class MainActivity extends ReactActivity {
            @Override
            protected String getMainComponentName() {
              return "SuppliesTracker";
            }
          }
          EOF

          # 3. Création du fichier de thèmes
          cat <<EOF > app/src/main/res/values/styles.xml
          <resources><style name="AppTheme" parent="android:Theme.Material.Light.NoActionBar"></style></resources>
          EOF
          
          # 4. Manifest
          cat <<EOF > app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.suppliestracker">
              <application android:label="Supplies Tracker" android:theme="@style/AppTheme">
                  <activity android:name=".MainActivity" android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" /><category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF
      - name: Bundle JavaScript (The Offline Core)
        script: |
          # On crée le bundle qui contient tout ton code offline
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      - name: Build Signed APK
        script: |
          cd android
          # On force le wrapper et on compile
          curl -L https://raw.githubusercontent.com/gradle/gradle/v8.0.2/gradlew -o gradlew
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - ton-email@ici.com
