workflows:
  react-web-workflow:
    name: React Web Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      node: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build React App
        script: |
          # On force le CI=false directement dans la commande
          CI=false npm run build
    artifacts:
      - build/**
    publishing:
      email:
        recipients:
          - votre-email@exemple.com
          
