workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup Project Structure
        script: |
          # 1. Préparation des fichiers source
          cp "App (1).js" App.js || true
          
          # 2. Installation des dépendances et du CLI
          npm install @react-native-community/cli @react-native-community/cli-platform-android --save-dev
          npm install
          
          # 3. Création et nettoyage du dossier Android
          mkdir -p android/app
          cp build.gradle.txt android/build.gradle || true
          cp "build.gradle (1).txt" android/app/build.gradle || true
          cp settings.gradle.txt android/settings.gradle || true
          
          # 4. Génération propre du moteur Gradle (Gradle Wrapper)
          # On utilise une version stable pour React Native 0.72
          cd android && gradle wrapper --gradle-version 8.0.2 && cd ..

      - name: Bundle JavaScript
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          # On augmente la mémoire allouée à Gradle pour éviter le StackOverflow
          export GRADLE_OPTS="-Xmx2048m -Xss4m"
          ./gradlew assembleDebug --no-daemon --stacktrace
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - votre-email@exemple.com
