workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup Project Structure
        script: |
          # 1. Préparation du code JS
          cp "App (1).js" App.js || true
          
          # 2. Installation propre des dépendances
          npm install --quiet
          
          # 3. Création de l'arborescence Android standard
          mkdir -p android/app/src/main/java/com/suppliestracker
          mkdir -p android/app/src/main/res/drawable
          mkdir -p android/app/src/main/res/values
          mkdir -p android/app/src/main/assets
          
          # 4. Génération d'un settings.gradle robuste
          cat <<EOF > android/settings.gradle
          rootProject.name = 'SuppliesTracker'
          apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
          include ':app'
          EOF

          # 5. Génération d'un build.gradle (root) propre
          cat <<EOF > android/build.gradle
          buildscript {
              repositories { google(); mavenCentral() }
              dependencies { classpath("com.android.tools.build:gradle:8.0.2") }
          }
          allprojects { repositories { google(); mavenCentral() } }
          EOF

          # 6. Génération d'un build.gradle (app) compatible React Native 0.72
          cat <<EOF > android/app/build.gradle
          apply plugin: "com.android.application"
          apply plugin: "com.facebook.react"

          android {
              namespace "com.suppliestracker"
              compileSdkVersion 33
              defaultConfig {
                  applicationId "com.suppliestracker"
                  minSdkVersion 21
                  targetSdkVersion 33
                  versionCode 1
                  versionName "1.0"
              }
          }
          
          dependencies {
              implementation("com.facebook.react:react-android")
          }
          apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
          EOF

      - name: Bundle JavaScript
        script: |
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build APK
        script: |
          cd android
          gradle wrapper --gradle-version 8.0.2
          chmod +x gradlew
          export GRADLE_OPTS="-Xmx2048m -Xss4m"
          ./gradlew assembleDebug --no-daemon
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - ton-email@exemple.com
