workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - keystore_credentials # Optionnel si vous signez l'app
      vars:
        PACKAGE_NAME: "com.suppliestracker.app"
      node: 18.x
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install Android SDK components
        script: |
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-33"
      - name: Build Android APK
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - VOTRE_EMAIL@ICI.COM
