workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup Project Structure
        script: |
          # 1. Préparation du code source
          cp "App (1).js" App.js || true
          
          # 2. Nettoyage total (essentiel sur Codemagic)
          rm -rf android node_modules package-lock.json
          
          # 3. Génération du projet natif
          # On installe le CLI d'abord
          npm install @react-native-community/cli-platform-android --save-dev
          
          # Initialisation sans l'option --force pour éviter l'erreur
          npx react-native@0.72.6 init SuppliesTracker --version 0.72.6 --skip-install --npm --directory .
          
          # 4. Installation des modules
          npm install
          
          # 5. Création du Gradle Wrapper (si manquant)
          if [ ! -d "android" ]; then echo "ERREUR: Dossier android non créé"; exit 1; fi
          cd android && gradle wrapper --gradle-version 8.0.2 && cd ..

      - name: Bundle JavaScript
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          # Paramètres de mémoire pour éviter le StackOverflow
          export GRADLE_OPTS="-Xmx2048m -Xss4m"
          ./gradlew assembleDebug --no-daemon
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - votre-email@exemple.com
