workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup Project Structure
        script: |
          # 1. Préparation des fichiers source
          cp "App (1).js" App.js || true
          
          # 2. Nettoyage complet du dossier de travail
          # On garde seulement les fichiers vitaux pour l'init
          mkdir ../temp_source
          cp package.json App.js index.js app.json ../temp_source/ || true
          rm -rf *
          cp ../temp_source/* .
          
          # 3. Génération de la structure Android
          # On utilise --skip-install pour ne pas perdre de temps ici
          npx react-native@0.72.6 init SuppliesTracker --version 0.72.6 --skip-install --npm --directory . --non-interactive
          
          # 4. Installation massive des dépendances AU BON ENDROIT
          npm install
          npm install @react-native-community/cli-platform-android --save-dev
          
          # 5. Injection forcée des liens (Auto-link) avec chemins RELATIFS directs
          # On écrase les lignes problématiques générées par l'init
          echo "rootProject.name = 'SuppliesTracker'" > android/settings.gradle
          echo "apply from: file(\"../node_modules/@react-native-community/cli-platform-android/native_modules.gradle\"); applyNativeModulesSettingsGradle(settings)" >> android/settings.gradle
          echo "include ':app'" >> android/settings.gradle
          
          echo "apply plugin: \"com.android.application\"" > android/app/build.gradle
          echo "apply from: file(\"../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle\"); applyNativeModulesAppBuildGradle(project)" >> android/app/build.gradle
          # On ajoute le reste du contenu minimal pour le build.gradle de l'app
          cat <<EOF >> android/app/build.gradle
          android {
              namespace "com.suppliestracker"
              compileSdkVersion 33
              defaultConfig {
                  applicationId "com.suppliestracker"
                  minSdkVersion 21
                  targetSdkVersion 33
                  versionCode 1
                  versionName "1.0"
              }
          }
          dependencies {
              implementation("com.facebook.react:react-android")
          }
          EOF

      - name: Bundle JavaScript
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build APK
        script: |
          cd android
          # On s'assure que le wrapper est présent
          gradle wrapper --gradle-version 8.0.2
          chmod +x gradlew
          export GRADLE_OPTS="-Xmx2048m -Xss4m"
          ./gradlew assembleDebug --no-daemon
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - votre-email@exemple.com
