workflows:
  android-apk:
    name: Build Android APK
    instance_type: mac_mini_m1
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build APK
        script: |
          # Cette fois, le dossier android existe, donc ça va passer
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - ton-email@ici.com
