workflows:
  android-apk:
    name: Build Android APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Initialize Project
        script: |
          npm install
          npx react-native init TempApp --version 0.72.6 --skip-install
          cp -r TempApp/android .
          chmod +x android/gradlew
      - name: Build APK
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - ton-email@ici.com
