workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup Project Structure
        script: |
          # 1. On prépare l'application (renommage du fichier principal)
          cp "App (1).js" App.js || true
          
          # 2. On installe le CLI React Native indispensable
          npm install @react-native-community/cli @react-native-community/cli-platform-android --save-dev
          npm install
          
          # 3. SOLUTION RADICALE : On recrée un dossier Android propre
          # On supprime l'ancien qui cause le StackOverflow
          rm -rf android
          
          # On génère un dossier Android tout neuf version 0.72.6
          npx react-native@0.72.6 init SuppliesTracker --version 0.72.6 --skip-install --npm --directory . --force
          
          # 4. On réinstalle les modules pour l'auto-linking
          npm install

      - name: Bundle JavaScript
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          # Correction du StackOverflow par l'augmentation de la pile mémoire
          export GRADLE_OPTS="-Xmx2048m -Xss4m"
          ./gradlew assembleDebug --no-daemon
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - votre-email@exemple.com
