workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install react-native-sqlite-storage lucide-react-native react-native-svg react-native-linear-gradient react-native-image-picker react-native-signature-canvas react-native-webview
      - name: Setup Android Structure & Assets
        script: |
          cd android
          mkdir -p app/src/main/res/values
          mkdir -p app/src/main/assets
          
          # Thème et Manifest
          cat <<EOF > app/src/main/res/values/styles.xml
          <resources><style name="AppTheme" parent="android:Theme.Material.Light.NoActionBar"></style></resources>
          EOF
          cat <<EOF > app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.suppliestracker">
              <application android:label="Supplies Tracker" android:theme="@style/AppTheme">
                  <activity android:name=".MainActivity" android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" /><category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF
      - name: Bundle JavaScript (The Offline Core)
        script: |
          # Cette étape met ton code App.js DANS l'APK pour le mode Offline
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      - name: Build Signed APK
        script: |
          cd android
          # On génère une version "Debug" car elle est auto-signée et installable immédiatement
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - ton-email@ici.com
