workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup Project Structure
        script: |
          # 1. Vérification/Création du point d'entrée JS
          cp "App (1).js" App.js || true
          if [ ! -f index.js ]; then
            echo "import {AppRegistry} from 'react-native'; import App from './App'; AppRegistry.registerComponent('SuppliesTracker', () => App);" > index.js
          fi
          
          # 2. Installation des dépendances
          npm install --quiet
          
          # 3. Structure Java
          mkdir -p android/app/src/main/java/com/suppliestracker
          mkdir -p android/app/src/main/res/drawable
          mkdir -p android/app/src/main/res/values
          mkdir -p android/app/src/main/assets
          
          # 4. Fichiers Java sources
          cat <<EOF > android/app/src/main/java/com/suppliestracker/MainActivity.java
          package com.suppliestracker;
          import com.facebook.react.ReactActivity;
          public class MainActivity extends ReactActivity {
            @Override
            protected String getMainComponentName() { return "SuppliesTracker"; }
          }
          EOF

          cat <<EOF > android/app/src/main/java/com/suppliestracker/MainApplication.java
          package com.suppliestracker;
          import android.app.Application;
          import com.facebook.react.ReactApplication;
          import com.facebook.react.ReactNativeHost;
          import com.facebook.react.ReactPackage;
          import com.facebook.react.shell.MainReactPackage;
          import com.facebook.soloader.SoLoader;
          import java.util.Arrays;
          import java.util.List;
          public class MainApplication extends Application implements ReactApplication {
            private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
              @Override
              public boolean getUseDeveloperSupport() { return false; }
              @Override
              protected List<ReactPackage> getPackages() { return Arrays.<ReactPackage>asList(new MainReactPackage()); }
              @Override
              protected String getJSMainModuleName() { return "index"; }
            };
            @Override
            public ReactNativeHost getReactNativeHost() { return mReactNativeHost; }
            @Override
            public void onCreate() { super.onCreate(); SoLoader.init(this, false); }
          }
          EOF

          # 5. Configuration Gradle
          echo "rootProject.name = 'SuppliesTracker'" > android/settings.gradle
          echo "include ':app'" >> android/settings.gradle

          cat <<EOF > android/build.gradle
          buildscript {
              repositories { google(); mavenCentral() }
              dependencies { classpath("com.android.tools.build:gradle:7.4.2") }
          }
          allprojects {
              repositories {
                  google()
                  mavenCentral()
                  maven { url "$CM_BUILD_DIR/node_modules/react-native/android" }
              }
          }
          EOF

          cat <<EOF > android/app/build.gradle
          apply plugin: "com.android.application"
          android {
              namespace "com.suppliestracker"
              compileSdkVersion 33
              defaultConfig {
                  applicationId "com.suppliestracker"
                  minSdkVersion 21
                  targetSdkVersion 33
                  versionCode 1
                  versionName "1.0"
              }
              // Force l'ignorance des conflits de métadonnées
              packagingOptions {
                  pickFirst '**/libc++_shared.so'
              }
          }
          dependencies {
              implementation "com.facebook.react:react-android:0.72.6"
              implementation "com.facebook.react:hermes-android:0.72.6"
          }
          EOF

          cat <<EOF > android/app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.suppliestracker">
              <uses-permission android:name="android.permission.INTERNET" />
              <application android:name=".MainApplication" android:label="SuppliesTracker" android:theme="@style/Theme.AppCompat.Light.NoActionBar">
                  <activity android:name=".MainActivity" android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF

      - name: Bundle JavaScript
        script: |
          npx react-native bundle --platform android --dev false --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build APK
        script: |
          cd android
          gradle wrapper --gradle-version 7.5
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - ton-email@exemple.com
