workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup React Native Project
        script: |
          # 1. Sauvegarde de ton code
          cp App.js ../App.js.backup
          
          # 2. On vide tout pour repartir sur une base saine
          rm -rf *
          
          # 3. On crée un vrai projet React Native complet (version 0.72.6)
          # Cela va créer TOUS les fichiers Java et Gradle correctement
          npx react-native@0.72.6 init SuppliesTracker --version 0.72.6 --skip-install --npm --directory .
          
          # 4. On remet ton code métier (Offline)
          mv ../App.js.backup App.js
          
          # 5. On installe les dépendances
          npm install
          npm install react-native-sqlite-storage lucide-react-native react-native-svg react-native-linear-gradient react-native-image-picker react-native-signature-canvas react-native-webview
      - name: Bundle JavaScript
        script: |
          # On prépare le pack pour le mode sans internet
          mkdir -p android/app/src/main/assets
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - ton-email@ici.com
