workflows:
  android-apk:
    name: Build SuppliesTracker APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Build and Package APK
        script: |
          sdk use java 17.0.7-sem || true
          cp "App (1).js" App.js || true
          
          cat <<EOF > index.js
          import {AppRegistry} from 'react-native';
          import App from './App';
          AppRegistry.registerComponent('SuppliesTracker', () => App);
          EOF

          npm install --quiet

          # --- RÉÉCRITURE TOTALE DU BUILD.GRADLE DE SQLITE ---
          # On écrase le fichier original par une version propre et compatible
          mkdir -p node_modules/react-native-sqlite-storage/src/android
          cat <<EOF > node_modules/react-native-sqlite-storage/src/android/build.gradle
          buildscript {
              repositories { google(); mavenCentral() }
              dependencies { classpath("com.android.tools.build:gradle:7.4.2") }
          }
          apply plugin: 'com.android.library'
          android {
              compileSdkVersion 33
              namespace "org.pgsqlite"
              defaultConfig {
                  minSdkVersion 21
                  targetSdkVersion 33
              }
              lintOptions { abortOnError false }
          }
          repositories { google(); mavenCentral() }
          dependencies {
              implementation "com.facebook.react:react-android:0.72.6"
          }
          EOF
          # ---------------------------------------------------

          rm -rf android
          mkdir -p android/app/src/main/java/com/suppliestracker
          mkdir -p android/app/src/main/res/values
          mkdir -p android/app/src/main/assets

          echo "rootProject.name = 'SuppliesTracker'" > android/settings.gradle
          echo "include ':app'" >> android/settings.gradle
          echo "include ':react-native-sqlite-storage'" >> android/settings.gradle
          echo "project(':react-native-sqlite-storage').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-sqlite-storage/src/android')" >> android/settings.gradle

          cat <<EOF > android/gradle.properties
          android.useAndroidX=true
          android.enableJetifier=true
          EOF

          cat <<EOF > android/build.gradle
          buildscript {
              repositories { google(); mavenCentral() }
              dependencies { classpath("com.android.tools.build:gradle:7.4.2") }
          }
          allprojects {
              repositories { 
                  google()
                  mavenCentral()
                  maven { url "\$projectDir/../node_modules/react-native/android" } 
              }
          }
          EOF

          cat <<EOF > android/app/build.gradle
          apply plugin: "com.android.application"
          android {
              namespace "com.suppliestracker"
              compileSdkVersion 33
              defaultConfig {
                  applicationId "com.suppliestracker"
                  minSdkVersion 21
                  targetSdkVersion 33
                  versionCode 1
                  versionName "1.0"
                  multiDexEnabled true
              }
              buildTypes {
                  debug {
                      matchingFallbacks = ['release']
                  }
              }
          }
          dependencies {
              implementation "com.facebook.react:react-android:0.72.6"
              implementation "com.facebook.react:hermes-android:0.72.6"
              implementation project(':react-native-sqlite-storage')
              implementation "androidx.appcompat:appcompat:1.4.1"
              implementation "androidx.multidex:multidex:2.0.1"
          }
          EOF

          cat <<EOF > android/app/src/main/java/com/suppliestracker/MainActivity.java
          package com.suppliestracker;
          import com.facebook.react.ReactActivity;
          public class MainActivity extends ReactActivity {
            @Override protected String getMainComponentName() { return "SuppliesTracker"; }
          }
          EOF

          cat <<EOF > android/app/src/main/java/com/suppliestracker/MainApplication.java
          package com.suppliestracker;
          import android.app.Application;
          import androidx.multidex.MultiDexApplication;
          import com.facebook.react.ReactApplication;
          import com.facebook.react.ReactNativeHost;
          import com.facebook.react.ReactPackage;
          import com.facebook.react.shell.MainReactPackage;
          import com.facebook.soloader.SoLoader;
          import org.pgsqlite.SQLitePluginPackage;
          import java.util.Arrays;
          import java.util.List;
          public class MainApplication extends MultiDexApplication implements ReactApplication {
            private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
              @Override public boolean getUseDeveloperSupport() { return false; }
              @Override protected List<ReactPackage> getPackages() { 
                return Arrays.<ReactPackage>asList(new MainReactPackage(), new SQLitePluginPackage()); 
              }
              @Override protected String getJSMainModuleName() { return "index"; }
              @Override protected String getJSBundleFile() { return "assets://index.android.bundle"; }
            };
            @Override public ReactNativeHost getReactNativeHost() { return mReactNativeHost; }
            @Override public void onCreate() { super.onCreate(); SoLoader.init(this, false); }
          }
          EOF

          cat <<EOF > android/app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.suppliestracker">
              <uses-permission android:name="android.permission.INTERNET" />
              <application android:name=".MainApplication" android:label="SuppliesTracker" android:theme="@style/Theme.AppCompat.Light.NoActionBar">
                  <activity android:name=".MainActivity" android:exported="true" android:launchMode="singleTask">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF

          npx react-native bundle --platform android --dev false --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

          cd android
          gradle wrapper --gradle-version 7.5
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon || exit 1
          
          mkdir -p \$CM_EXPORT_DIR
          find . -name "*.apk" -exec cp {} \$CM_EXPORT_DIR/app-debug.apk \;

    artifacts:
      - \$CM_EXPORT_DIR/*.apk
