workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup Project Structure
        script: |
          # 1. Préparation du code
          cp "App (1).js" App.js || true
          
          # 2. Création de l'arborescence Android
          mkdir -p android/app/src/main/res/drawable
          mkdir -p android/app/src/main/res/values
          mkdir -p android/app/src/main/assets
          
          # 3. Placement et CORRECTION des fichiers Gradle
          cp settings.gradle.txt android/settings.gradle || true
          cp build.gradle.txt android/build.gradle || true
          cp "build.gradle (1).txt" android/app/build.gradle || true

          # 4. Ajout de l'Auto-linking (L'étape manquante qui causait l'erreur)
          echo "apply from: file(\"../node_modules/@react-native-community/cli-platform-android/native_modules.gradle\"); applyNativeModulesSettingsGradle(settings)" >> android/settings.gradle
          echo "apply from: file(\"../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle\"); applyNativeModulesAppBuildGradle(project)" >> android/app/build.gradle

          # 5. Création du Manifest indispensable
          cat <<EOF > android/app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.suppliestracker">
              <uses-permission android:name="android.permission.INTERNET" />
              <application android:label="SuppliesTracker" android:allowBackup="false" android:theme="@style/Theme.AppCompat.Light.NoActionBar">
                  <activity android:name=".MainActivity" android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF

          # 6. Installation des dépendances
          npm install
          
      - name: Bundle JavaScript
        script: |
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build APK
        script: |
          cd android
          gradle wrapper --gradle-version 8.0.2
          chmod +x gradlew
          export GRADLE_OPTS="-Xmx2048m -Xss4m"
          ./gradlew assembleDebug --no-daemon
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - votre-email@exemple.com
