workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup Project Structure
        script: |
          # 1. On se déplace dans le dossier parent pour créer un projet 100% propre
          cd ..
          rm -rf clean_project
          npx react-native@0.72.6 init SuppliesTracker --version 0.72.6 --skip-install --npm --non-interactive
          
          # 2. On rapatrie la structure propre vers le dossier de travail
          cp -R SuppliesTracker/* $CM_BUILD_DIR/
          cd $CM_BUILD_DIR
          
          # 3. Restauration de votre code
          cp "App (1).js" App.js || true
          
          # 4. Installation des dépendances (Nécessaire pour l'Auto-link)
          npm install
          npm install react-native-sqlite-storage lucide-react-native react-native-svg react-native-linear-gradient react-native-image-picker react-native-signature-canvas react-native-webview

          # 5. RÉPARATION DE L'AUTO-LINK (Étape manquante précédemment)
          # On injecte les scripts qui permettent à Android de voir les plugins
          echo "apply from: file(\"../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle\"); applyNativeModulesAppBuildGradle(project)" >> android/app/build.gradle
          echo "apply from: file(\"../node_modules/@react-native-community/cli-platform-android/native_modules.gradle\"); applyNativeModulesSettingsGradle(settings)" >> android/settings.gradle

      - name: Bundle JavaScript
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build APK
        script: |
          cd android
          # On force la création du wrapper
          gradle wrapper --gradle-version 8.0.2
          chmod +x gradlew
          
          # Augmentation radicale de la mémoire pour éviter le StackOverflow
          export GRADLE_OPTS="-Xmx2048m -Xss4m"
          ./gradlew assembleDebug --no-daemon
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - votre-email@exemple.com
