workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup Project Structure
        script: |
          # 1. Préparation du code
          cp "App (1).js" App.js || true
          
          # 2. Installation forcée (On s'assure que le dossier existe)
          npm install --quiet
          
          # 3. Création de la structure Android
          mkdir -p android/app/src/main/res/drawable
          mkdir -p android/app/src/main/res/values
          mkdir -p android/app/src/main/assets
          
          # 4. Copie de tes fichiers Gradle
          cp settings.gradle.txt android/settings.gradle || true
          cp build.gradle.txt android/build.gradle || true
          cp "build.gradle (1).txt" android/app/build.gradle || true

          # 5. RE-LIAGE MANUEL (La solution à ton erreur)
          # On crée physiquement le fichier manquant s'il n'est pas trouvé par Gradle
          # pour forcer le passage de l'étape de configuration
          mkdir -p node_modules/@react-native-community/cli-platform-android
          cp node_modules/react-native/scripts/native_modules.gradle node_modules/@react-native-community/cli-platform-android/ || true

      - name: Bundle JavaScript
        script: |
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build APK
        script: |
          cd android
          # On génère le wrapper AVANT de lancer quoi que ce soit
          gradle wrapper --gradle-version 8.0.2
          chmod +x gradlew
          
          # On nettoie et on build
          export GRADLE_OPTS="-Xmx2048m -Xss4m"
          ./gradlew assembleDebug --no-daemon
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - ton-email@exemple.com
