workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup Project Structure
        script: |
          # 1. Préparation du code source
          cp "App (1).js" App.js || true
          
          # 2. NETTOYAGE RADICAL
          # On supprime tout ce qui pourrait empêcher une installation propre
          rm -rf android
          rm -rf node_modules
          rm -f package-lock.json
          
          # 3. GÉNÉRATION FORCEE
          # On installe le CLI et on force la création du dossier Android
          npm install @react-native-community/cli@latest @react-native-community/cli-platform-android@latest --save-dev
          
          # On crée un projet temporaire pour être sûr d'avoir tous les fichiers
          npx react-native@0.72.6 init TempApp --version 0.72.6 --skip-install --npm
          
          # On récupère le dossier android TOUT NEUF
          mv TempApp/android .
          mv TempApp/app.json .
          
          # 4. INSTALLATION DES DÉPENDANCES
          npm install
          npm install react-native-sqlite-storage lucide-react-native react-native-svg react-native-linear-gradient react-native-image-picker react-native-signature-canvas react-native-webview

      - name: Bundle JavaScript
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build APK
        script: |
          cd android
          # On s'assure que le fichier gradlew est exécutable
          chmod +x gradlew
          # On augmente la mémoire pour éviter le StackOverflow
          export GRADLE_OPTS="-Xmx2048m -Xss4m"
          ./gradlew assembleDebug --no-daemon
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - votre-email@exemple.com
