workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup Project Structure
        script: |
          # 1. On prépare les fichiers JS
          cp "App (1).js" App.js || true
          
          # 2. Nettoyage de sécurité
          rm -rf android node_modules package-lock.json
          
          # 3. On génère un dossier Android NEUF
          # On utilise npx pour l'initier sans dépendre du dossier node_modules local
          npx react-native@0.72.6 init SuppliesTracker --version 0.72.6 --skip-install --npm --directory . --force
          
          # 4. INSTALLATION CRUCIALE
          # On installe TOUT maintenant pour que l'auto-linking trouve les chemins
          npm install
          npm install @react-native-community/cli-platform-android --save-dev
          
          # Installation des bibliothèques de votre code
          npm install react-native-sqlite-storage lucide-react-native react-native-svg react-native-linear-gradient react-native-image-picker react-native-signature-canvas react-native-webview

      - name: Bundle JavaScript
        script: |
          # Préparation du bundle pour le mode hors-ligne
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          # Correction de la mémoire pour éviter le StackOverflow
          export GRADLE_OPTS="-Xmx2048m -Xss4m"
          ./gradlew assembleDebug --no-daemon
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - votre-email@exemple.com
