workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup Project Structure
        script: |
          # 1. On prépare l'application
          cp "App (1).js" App.js || true
          
          # 2. Installation forcée du CLI
          npm install @react-native-community/cli @react-native-community/cli-platform-android --save-dev
          npm install
          
          # 3. GÉNÉRATION RADICALE : On crée un projet neuf à côté et on vole son dossier android
          # Cela garantit d'avoir un dossier 'android' 100% propre et complet
          cd ..
          npx react-native@0.72.6 init CleanProject --version 0.72.6 --skip-install --npm
          cd $CM_BUILD_DIR
          
          # On remplace l'ancien dossier android par le tout neuf
          rm -rf android
          cp -R ../CleanProject/android .
          
          # 4. On injecte tes fichiers Gradle personnalisés par-dessus
          cp build.gradle.txt android/build.gradle || true
          cp "build.gradle (1).txt" android/app/build.gradle || true
          cp settings.gradle.txt android/settings.gradle || true

      - name: Bundle JavaScript
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build APK
        script: |
          # On n'utilise PAS ./gradlew (qui pose problème)
          # On utilise 'gradle' installé sur la machine Codemagic
          cd android
          gradle assembleDebug --no-daemon
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - ton-email@exemple.com
