workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup Project Structure
        script: |
          # 1. Préparation des fichiers JS
          cp "App (1).js" App.js || true
          
          # 2. Création forcée de la structure Android
          mkdir -p android/app
          
          # 3. Renommage et placement des fichiers Gradle (on enlève le .txt)
          cp build.gradle.txt android/build.gradle || true
          cp "build.gradle (1).txt" android/app/build.gradle || true
          cp settings.gradle.txt android/settings.gradle || true
          
          # 4. Installation des outils et dépendances
          npm install @react-native-community/cli @react-native-community/cli-platform-android --save-dev
          npm install
          
          # 5. GÉNÉRATION DU GRADLEW MANQUANT
          # Cette commande installe le moteur Gradle directement dans le dossier
          cd android && gradle wrapper --gradle-version 7.5.1 && cd ..

      - name: Bundle JavaScript
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build APK
        script: |
          cd android
          # On donne les droits d'exécution au fichier qu'on vient de générer
          chmod +x gradlew
          # On lance le build
          ./gradlew assembleDebug --no-daemon
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - votre-email@exemple.com
