workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install react-native-sqlite-storage lucide-react-native react-native-svg react-native-linear-gradient react-native-image-picker react-native-signature-canvas react-native-webview
      - name: Force Gradle Wrapper
        script: |
          cd android
          # On télécharge le moteur de build directement puisqu'il manque
          curl -L https://raw.githubusercontent.com/gradle/gradle/master/gradlew -o gradlew
          chmod +x gradlew
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease --stacktrace
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - votre-email@ici.com
