workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    scripts:
      - name: Setup Project Structure
        script: |
          # On renomme le fichier App
          cp "App (1).js" App.js || true
          
          # On s'assure que les fichiers Gradle sont au bon endroit
          mkdir -p android/app
          cp build.gradle.txt android/build.gradle || true
          cp "build.gradle (1).txt" android/app/build.gradle || true
          cp settings.gradle.txt android/settings.gradle || true
          
          # Installation du CLI pour éviter l'erreur "depends on @react-native-community/cli"
          npm install @react-native-community/cli @react-native-community/cli-platform-android --save-dev
          npm install
          
      - name: Bundle JavaScript
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res
            
      - name: Build APK
        script: |
          # Si gradlew manque, on le génère
          cd android
          npm install -g corepack
          # Commande de secours pour lancer le build sans gradlew si nécessaire
          gradle assembleDebug
