workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    scripts:
      - name: Setup Project Structure
        script: |
          # 1. On prépare le fichier principal
          cp "App (1).js" App.js || true
          
          # 2. Création MANUELLE de l'arborescence Android
          # C'est cette étape qui remplace le 'npx react-native init' qui échouait
          mkdir -p android/app/src/main/res/drawable
          mkdir -p android/app/src/main/res/values
          mkdir -p android/app/src/main/assets
          
          # 3. Placement de vos fichiers Gradle (en enlevant le .txt)
          cp build.gradle.txt android/build.gradle || true
          cp "build.gradle (1).txt" android/app/build.gradle || true
          cp settings.gradle.txt android/settings.gradle || true
          
          # 4. Création du Manifest minimal (Indispensable pour Android)
          cat <<EOF > android/app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.suppliestracker">
              <uses-permission android:name="android.permission.INTERNET" />
              <application android:label="SuppliesTracker" android:allowBackup="false" android:theme="@style/Theme.AppCompat.Light.NoActionBar">
                  <activity android:name=".MainActivity" android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
                  <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
              </application>
          </manifest>
          EOF

          # 5. Installation des dépendances
          npm install
          
      - name: Bundle JavaScript
        script: |
          # Génération du bundle (le code de l'app) dans les assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build APK
        script: |
          cd android
          # On génère le fichier gradlew qui manquait
          gradle wrapper --gradle-version 8.0.2
          chmod +x gradlew
          
          # Build final
          export GRADLE_OPTS="-Xmx2048m -Xss4m"
          ./gradlew assembleDebug --no-daemon
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - votre-email@exemple.com
