workflows:
  android-apk:
    name: Build Android Offline APK
    instance_type: mac_mini_m1
    scripts:
      - name: Setup Project Structure
        script: |
          # 1. Préparation des fichiers
          cp "App (1).js" App.js || true
          
          # 2. Installation du CLI et des dépendances
          npm install @react-native-community/cli @react-native-community/cli-platform-android --save-dev
          npm install
          
          # 3. Réparation automatique des fichiers Gradle (L'étape CRUCIALE)
          mkdir -p android/app
          cp build.gradle.txt android/build.gradle || true
          cp "build.gradle (1).txt" android/app/build.gradle || true
          cp settings.gradle.txt android/settings.gradle || true

          # 4. Injection de l'auto-link (Pour SQLite, Svg, Gradient...)
          # Cette ligne ajoute le support des bibliothèques tierces dans le build
          echo "apply from: file(\"../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle\"); applyNativeModulesAppBuildGradle(project)" >> android/app/build.gradle
          echo "apply from: file(\"../node_modules/@react-native-community/cli-platform-android/native_modules.gradle\"); applyNativeModulesSettingsGradle(settings)" >> android/settings.gradle

      - name: Bundle JavaScript
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res
            
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          # Utilisation de --no-daemon et --stacktrace pour voir l'erreur précise si ça échoue
          ./gradlew assembleDebug --no-daemon --stacktrace
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - votre-email@exemple.com
